package com.sondh.gishop.mapper;

import com.sondh.gishop.entity.OrderDetail;
import com.sondh.gishop.entity.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    long countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int insert(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int insertSelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    OrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByExampleSelective(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByExample(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByPrimaryKeySelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByPrimaryKey(OrderDetail row);
}