package com.sondh.gishop.mapper;

import com.sondh.gishop.entity.UserPayment;
import com.sondh.gishop.entity.UserPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    long countByExample(UserPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int deleteByExample(UserPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int insert(UserPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int insertSelective(UserPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    List<UserPayment> selectByExample(UserPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    UserPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByExampleSelective(@Param("row") UserPayment row, @Param("example") UserPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByExample(@Param("row") UserPayment row, @Param("example") UserPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByPrimaryKeySelective(UserPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    int updateByPrimaryKey(UserPayment row);
}