package com.sondh.gishop.entity;

import java.util.Date;

public class Discount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.discount_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String discountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.description
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.discount_percent
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Short discountPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.active
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.id
     *
     * @return the value of discount.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.id
     *
     * @param id the value for discount.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.discount_name
     *
     * @return the value of discount.discount_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getDiscountName() {
        return discountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.discount_name
     *
     * @param discountName the value for discount.discount_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDiscountName(String discountName) {
        this.discountName = discountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.description
     *
     * @return the value of discount.description
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.description
     *
     * @param description the value for discount.description
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.discount_percent
     *
     * @return the value of discount.discount_percent
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Short getDiscountPercent() {
        return discountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.discount_percent
     *
     * @param discountPercent the value for discount.discount_percent
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDiscountPercent(Short discountPercent) {
        this.discountPercent = discountPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.active
     *
     * @return the value of discount.active
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.active
     *
     * @param active the value for discount.active
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.create_at
     *
     * @return the value of discount.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.create_at
     *
     * @param createAt the value for discount.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.modified_at
     *
     * @return the value of discount.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.modified_at
     *
     * @param modifiedAt the value for discount.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount.del_flag
     *
     * @return the value of discount.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount.del_flag
     *
     * @param delFlag the value for discount.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}