package com.sondh.gishop.entity;

import java.util.Date;

public class OrderItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.order_detail_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.product_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.id
     *
     * @return the value of order_items.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.id
     *
     * @param id the value for order_items.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.order_detail_id
     *
     * @return the value of order_items.order_detail_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.order_detail_id
     *
     * @param orderDetailId the value for order_items.order_detail_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.product_id
     *
     * @return the value of order_items.product_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.product_id
     *
     * @param productId the value for order_items.product_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.quantity
     *
     * @return the value of order_items.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.quantity
     *
     * @param quantity the value for order_items.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.create_at
     *
     * @return the value of order_items.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.create_at
     *
     * @param createAt the value for order_items.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.modified_at
     *
     * @return the value of order_items.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.modified_at
     *
     * @param modifiedAt the value for order_items.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}