package com.sondh.gishop.entity;

import java.util.Date;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.total
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Short total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.payment_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.user_id
     *
     * @return the value of order_detail.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.user_id
     *
     * @param userId the value for order_detail.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.total
     *
     * @return the value of order_detail.total
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Short getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.total
     *
     * @param total the value for order_detail.total
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setTotal(Short total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.payment_id
     *
     * @return the value of order_detail.payment_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.payment_id
     *
     * @param paymentId the value for order_detail.payment_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.create_at
     *
     * @return the value of order_detail.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.create_at
     *
     * @param createAt the value for order_detail.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.modified_at
     *
     * @return the value of order_detail.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.modified_at
     *
     * @param modifiedAt the value for order_detail.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}