package com.sondh.gishop.entity;

import java.util.Date;

public class PaymentDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.amount
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.provider
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.status
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_details.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.id
     *
     * @return the value of payment_details.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.id
     *
     * @param id the value for payment_details.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.amount
     *
     * @return the value of payment_details.amount
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.amount
     *
     * @param amount the value for payment_details.amount
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.provider
     *
     * @return the value of payment_details.provider
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.provider
     *
     * @param provider the value for payment_details.provider
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.status
     *
     * @return the value of payment_details.status
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.status
     *
     * @param status the value for payment_details.status
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.create_at
     *
     * @return the value of payment_details.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.create_at
     *
     * @param createAt the value for payment_details.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_details.modified_at
     *
     * @return the value of payment_details.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_details.modified_at
     *
     * @param modifiedAt the value for payment_details.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}