package com.sondh.gishop.entity;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.decription
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String decription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inventory_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Short price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer discountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.modified_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.decription
     *
     * @return the value of product.decription
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.decription
     *
     * @param decription the value for product.decription
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDecription(String decription) {
        this.decription = decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inventory_id
     *
     * @return the value of product.inventory_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inventory_id
     *
     * @param inventoryId the value for product.inventory_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Short getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setPrice(Short price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount_id
     *
     * @return the value of product.discount_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getDiscountId() {
        return discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount_id
     *
     * @param discountId the value for product.discount_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDiscountId(Integer discountId) {
        this.discountId = discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_date
     *
     * @return the value of product.create_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_date
     *
     * @param createDate the value for product.create_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.modified_date
     *
     * @return the value of product.modified_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.modified_date
     *
     * @param modifiedDate the value for product.modified_date
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.del_flag
     *
     * @return the value of product.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.del_flag
     *
     * @param delFlag the value for product.del_flag
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}