package com.sondh.gishop.entity;

import java.util.Date;

public class ProductInventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_inventory.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_inventory.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_inventory.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_inventory.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_inventory.id
     *
     * @return the value of product_inventory.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_inventory.id
     *
     * @param id the value for product_inventory.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_inventory.quantity
     *
     * @return the value of product_inventory.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_inventory.quantity
     *
     * @param quantity the value for product_inventory.quantity
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_inventory.create_at
     *
     * @return the value of product_inventory.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_inventory.create_at
     *
     * @param createAt the value for product_inventory.create_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_inventory.modified_at
     *
     * @return the value of product_inventory.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_inventory.modified_at
     *
     * @param modifiedAt the value for product_inventory.modified_at
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}