package com.sondh.gishop.entity;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_line1
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String addressLine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_line2
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String addressLine2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.city
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.postal_code
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.country
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.telephone
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_line1
     *
     * @return the value of user_address.address_line1
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_line1
     *
     * @param addressLine1 the value for user_address.address_line1
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_line2
     *
     * @return the value of user_address.address_line2
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_line2
     *
     * @param addressLine2 the value for user_address.address_line2
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.city
     *
     * @return the value of user_address.city
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.city
     *
     * @param city the value for user_address.city
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.postal_code
     *
     * @return the value of user_address.postal_code
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.postal_code
     *
     * @param postalCode the value for user_address.postal_code
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.country
     *
     * @return the value of user_address.country
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.country
     *
     * @param country the value for user_address.country
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.telephone
     *
     * @return the value of user_address.telephone
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.telephone
     *
     * @param telephone the value for user_address.telephone
     *
     * @mbg.generated Sat Jul 09 14:36:10 ICT 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
}